[package]
name = "project-template"
version = "0.0.0"
description = "A project template for the quick instantiation of rust projects."
authors = ["Daniel Balcomb <daniel.balcomb@gmail.com>"]
keywords = []
categories = []
homepage = "https://brace.rs/"
repository = "https://github.com/brace-rs/project-template"
documentation = "https://docs.rs/project-template"
readme = "README.md"
license = "MIT OR Apache-2.0"
edition = "2021"
