[package]
name = "project"
version = "0.1.0"
authors = ["Daniel Balcomb <daniel.balcomb@gmail.com>"]
description = "A project template for the quick instantiation of rust projects."
license = "MIT OR Apache-2.0"
edition = "2018"
