name: label
on:
  pull_request:
    types: [opened]
jobs:
  pr:
    name: pr
    runs-on: ubuntu-latest
    steps:
    - uses: TimonVS/pr-labeler-action@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
